steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/entrevista-funkol-api:$COMMIT_SHA',
        '.',
      ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/entrevista-funkol-api:$COMMIT_SHA']

  # Deploy container image to Cloud Run with environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'entrevista-funkol-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/entrevista-funkol-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,FIREBASE_SERVICE_ACCOUNT_BASE64=${_FIREBASE_SERVICE_ACCOUNT_BASE64}'

# Store the images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/entrevista-funkol-api:$COMMIT_SHA'

# Set timeout to 20 minutes
timeout: 1200s

# Substitution variables for the build
substitutions:
  _FIREBASE_SERVICE_ACCOUNT_BASE64: '' # Set this in the Cloud Build trigger UI
